### PR TITLE
Fixed: Install SQL scripts with package

### LINKED ISSUE #4: IOError: [Errno 2] No such file or directory: '../sql/artist_search_name.sql'
https://sentry.io/lidarr/metadata-api/issues/347214986/

```
IOError: [Errno 2] No such file or directory: '../sql/artist_search_name.sql'
(5 additional frame(s) were not displayed)
...
  File "lidarrmetadata/api.py", line 208, in search_route
    return search_artist()
  File "lidarrmetadata/api.py", line 182, in search_artist
    artists = search_providers[0].search_artist_name(query)

IOError: [Errno 2] No such file or directory: '../sql/artist_search_name.sql'
```

### PR DESCRIPTION
**Pull request by danielunderwood**
Install SQL scripts with package. Fixes #4.

### CODE REVIEW

File: lidarrmetadata/sql/artist_search_name.sql [hunk 1]
```diff
@@ -1,9 +1,8 @@
-SELECT
-  artist.gid,
-  artist.name,
-  ended,
```
Comment (Qstick) [inline lidarrmetadata/sql/artist_search_name.sql]: did you mean to get rid of `ended`

**Review by Qstick — APPROVED** [review]
